# Workflow名（好きな名前でOK）
name: Sample

# 実行するタイミング (github に push があったタイミングで実行する)
on: push

# 実行する処理の設定
jobs:

  # 実行する処理の名前
  sample:

    # 実行する環境 ( Docker Hub の CentOS8 を利用 )
    container:
      image: node:10.16-jessie
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1


    # 実行する処理やコマンドの指定
    steps:

      # Hello, World! を表示する
      - name: Sample
        run: echo Hello, World!
